import os
import re
from logging.config import fileConfig
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

from alembic import context
from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

# ---------------------------------------------------------------------------
# Importar TODOS los modelos para que SQLModel.metadata los conozca.
# Sin estos imports la migración autogenerated no ve las tablas.
# ---------------------------------------------------------------------------
import app.modules.auth.model          # noqa: F401  — Rol, UsuarioRol
import app.modules.refreshtokens.model  # noqa: F401  — RefreshToken
import app.modules.usuarios.model       # noqa: F401  — Usuario
import app.modules.direcciones.model    # noqa: F401  — DireccionEntrega
import app.modules.categorias.model     # noqa: F401  — Categoria
import app.modules.productos.model      # noqa: F401  — Producto, Ingrediente, etc.
import app.modules.pedidos.model        # noqa: F401  — Pedido, DetallePedido, etc.
import app.modules.pagos.model          # noqa: F401  — Pago

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def _get_sync_url() -> str:
    """
    Alembic necesita un driver síncrono (psycopg2).
    Convierte postgresql+asyncpg:// → postgresql+psycopg2://
    """
    url = os.environ.get("DATABASE_URL", config.get_main_option("sqlalchemy.url", ""))
    return re.sub(r"^postgresql\+asyncpg", "postgresql+psycopg2", url)


def run_migrations_offline() -> None:
    url = _get_sync_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = _get_sync_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
